# Generated by Django 4.2.1 on 2023-05-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_zerouser_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zerouser',
            name='env_id',
        ),
        migrations.RemoveField(
            model_name='zerouser',
            name='is_deployed',
        ),
    ]
